<?php
//
//return [
//    'up'=>
//        "-- MySQL Script generated by MySQL Workbench
//-- Wed 27 Jul 2022 04:59:00 PM MSK
//-- Model: New Model    Version: 1.0
//-- MySQL Workbench Forward Engineering
//
//SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
//SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
//SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
//
//
//-- -----------------------------------------------------
//CREATE SCHEMA IF NOT EXISTS `my_db_test_migration` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
//USE `my_db_test_migration` ;
//
//-- -----------------------------------------------------
//-- Table `my_db_test_migration`.`courses`
//-- -----------------------------------------------------
//CREATE TABLE IF NOT EXISTS `my_db_test_migration`.`courses` (
//  `course_id` INT NOT NULL AUTO_INCREMENT,
//  `title` VARCHAR(255) NOT NULL,
//  `author_id` INT NOT NULL,
//  `content` JSON NOT NULL,
//  `deleted` TINYINT NOT NULL DEFAULT '0',
//  PRIMARY KEY (`course_id`))
//ENGINE = InnoDB
//AUTO_INCREMENT = 14
//DEFAULT CHARACTER SET = utf8mb4
//COLLATE = utf8mb4_0900_ai_ci;
//
//
//-- -----------------------------------------------------
//-- Table `my_db_test_migration`.`roles`
//-- -----------------------------------------------------
//CREATE TABLE IF NOT EXISTS `my_db_test_migration`.`roles` (
//  `role_id` INT NOT NULL,
//  `role` VARCHAR(45) NOT NULL,
//  PRIMARY KEY (`role_id`))
//ENGINE = InnoDB
//DEFAULT CHARACTER SET = utf8mb4
//COLLATE = utf8mb4_0900_ai_ci;
//
//
//-- -----------------------------------------------------
//-- Table `my_db_test_migration`.`user_role`
//-- -----------------------------------------------------
//CREATE TABLE IF NOT EXISTS `my_db_test_migration`.`user_role` (
//  `user_id` INT NOT NULL,
//  `role_id` VARCHAR(45) NOT NULL,
//  PRIMARY KEY (`user_id`, `role_id`))
//ENGINE = InnoDB
//DEFAULT CHARACTER SET = utf8mb4
//COLLATE = utf8mb4_0900_ai_ci;
//
//
//-- -----------------------------------------------------
//-- Table `my_db_test_migration`.`users`
//-- -----------------------------------------------------
//CREATE TABLE IF NOT EXISTS `my_db_test_migration`.`users` (
//  `id` INT NOT NULL AUTO_INCREMENT,
//  `email` VARCHAR(45) NOT NULL,
//  `country` VARCHAR(45) NOT NULL,
//  `name` VARCHAR(45) NOT NULL,
//  `password` VARCHAR(255) NOT NULL,
//  `deleted` TINYINT NOT NULL,
//  `avatar_id` INT NOT NULL,
//  PRIMARY KEY (`id`),
//  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
//ENGINE = InnoDB
//AUTO_INCREMENT = 740
//DEFAULT CHARACTER SET = utf8mb4
//COLLATE = utf8mb4_0900_ai_ci;
//
//
//-- -----------------------------------------------------
//-- Table `my_db_test_migration`.`users_avatar`
//-- -----------------------------------------------------
//CREATE TABLE IF NOT EXISTS `my_db_test_migration`.`users_avatar` (
//  `avatar_id` INT NOT NULL AUTO_INCREMENT,
//  `picture_path` VARCHAR(45) NOT NULL,
//  PRIMARY KEY (`avatar_id`))
//ENGINE = InnoDB
//AUTO_INCREMENT = 32
//DEFAULT CHARACTER SET = utf8mb4
//COLLATE = utf8mb4_0900_ai_ci;
//
//
//SET SQL_MODE=@OLD_SQL_MODE;
//SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
//SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
//"
//    ,
//    "down"=>"DROP DATABASE my_db_test_migration;"
//];